# Generated by Django 4.0.3 on 2023-01-07 00:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ApplicantDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.CharField(choices=[('Mr.', 'Mr.'), ('Mrs.', 'Mrs.'), ('Ms.', 'Ms'), ('Rev.', 'Rev.'), ('Sr.', 'Sr.')], max_length=20)),
                ('Surname', models.CharField(max_length=255, verbose_name='Surname')),
                ('FirstName', models.CharField(max_length=255, verbose_name='First Name')),
                ('MiddleName', models.CharField(blank=True, max_length=255, null=True, verbose_name='Middle Name')),
                ('DateofBirth', models.DateField(verbose_name='Date of Birth')),
                ('Gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], max_length=20)),
            ],
        ),
    ]
